### ISSUE TITLE
Support large JSON reports

### ISSUE THREAD

**Issue by kenlyon** [davityavryan/yarn-audit-html#25]
I have a large react project with a lot (i.e. thousands) of out of date dependencies. The output of `yarn audit --json` is 15.9 GB in size. (I'll resist the urge to paste it here to show you!)

The `yarn-audit-html` command fails when used with this project. I'm pretty confident it's the amount of data that's causing it. I wondered if the issue might be the piping of the output of one command to the next. After a bit of investigation, I learned how to pass a file to stdin to be consumed by `yarn-audit-html`. (I'd recommend you document that as it might be useful.) I was then able to output the audit to a file and then pass that file to `yarn-audit-html`. Even then, I got the same error.

Is there any way that `yarn-audit-html` could be enhanced to handle such a large file?

Here is what I did. I tried the same thing using Git Bash, Command Prompt and PowerShell.

## Git Bash / Command Prompt
```
yarn audit --json > yarn-audit.json
yarn-audit-html < yarn-audit.json
```
### Error
```
C:\Users\<username>\AppData\Local\Yarn\Data\global\node_modules\yarn-audit-html\index.js:60
        stdin += chunk;
                 ^

RangeError: Invalid string length
    at ReadStream.<anonymous> (C:\Users\<username>\AppData\Local\Yarn\Data\global\node_modules\←[4myarn-audit-html←[24m\index.js:60:18)
←[90m    at ReadStream.emit (events.js:315:20)←[39m
←[90m    at emitReadable_ (internal/streams/readable.js:569:12)←[39m
←[90m    at processTicksAndRejections (internal/process/task_queues.js:79:21)←[39m
```
## PowerShell
```
yarn audit --json > yarn-audit.json
Get-Content yarn-audit.json | yarn-audit-html
```
### Error
```
Program 'yarn-audit-html.cmd' failed to run: capacity was less than the current size.
Parameter name: requiredLengthAt line:1 char:31
+ Get-Content yarn-audit.json | yarn-audit-html
+                               ~~~~~~~~~~~~~~~.
At line:1 char:1
+ Get-Content yarn-audit.json | yarn-audit-html
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ResourceUnavailable: (:) [], ApplicationFailedException
    + FullyQualifiedErrorId : NativeCommandFailed
```
## Other observations
* The `yarn audit` output is saved as `UTF-8` in Git Bash and Command Prompt, but `USC-2 LE BOM` in PowerShell, resulting in a file twice the size. If you're encountering this problem in PowerShell, it might help to convert the file to `UTF-8` before passing it to `yarn-audit-html`. (Not in my case, sadly.)

**Comment by davityavryan** [comment]
Hey @kenlyon ,

Thank for reaching out.
O wow, 15.9GB. ok. :/ hmmm :D

I personally haven't experienced this problem but I had big audit result which was resulting similar issue. I say similar because the solution might be the same.

I wonder if reading from file as a stream will help. As of audit JSON is [JSONL](https://jsonlines.org/) type I think it will be possible to read and generate result on the fly instead of reading everything and then having it output.

I will also try to take a look at encoding problem. :/ Although I don't use Windows. So I will appreciate help very much with this one.

Is there a way so that you can share your audit file somehow?

**Comment by davityavryan** [comment]
On a second glance. :/ this might be a different issue as of [index.js#59](https://github.com/davityavryan/yarn-audit-html/blob/7430f07e568952b1bdf5bffeccf1700533c02d70/index.js#L59) is in readable steam (as far as I understand). So having example file will help a lot to debug.

**Comment by kenlyon** [comment]
@davityavryan I have the file ready for you. (Zipped down to a much more manageable 477 MB. I'd prefer not to share it publicly, though. What would be the best way to send you the download link? I didn't see an email address or anything in your profile and I don't know if we can send a direct message here.

**Comment by davityavryan** [comment]
Hey @kenlyon, you can try to join https://gitter.im/yarn-audit-html where you can write me personal message. ;)
Let me know if you have any problems.

**Comment by davityavryan** [comment]
Ok. so my new approach worked (generate parse necessary info on the fly).
I will be able to change code in a way so that it will require static amount of ram and Node will not go crazy. Give me some time and I will push new version. ;)

p.s. `low: 7368, moderate: 171, high: 9558, critical: 0` OMG :D

**Comment by kenlyon** [comment]
@davityavryan Yes it's fair to say I'm a bit overdue on the audit - hence the need for a convenient tool to show it as HTML. You can't leave these package lock files untouched for too long or the world leaves you behind.

**Comment by davityavryan** [comment]
> You can't leave these package lock files untouched for too long or the world leaves you behind.

Yeap, yeap. That's the reason I introduced this tool.
Personally I am upgrading `devDependencies` in my packages once a month and non-dev-`dependencies` once in two months (to just not introduce many breaking changes(some times you can miss any specific migration point, or do a mistake)).

I guess in your case (so far that I saw), solution will be to upgrade `react-scripts` package, but personally I am not using it for a long time. I use [esbuild](https://esbuild.github.io/) which is 100+ times faster. If you don't want to handle manual configuration though, you can use webpack + esbuild. Give a try with [this example](https://github.com/davityavryan/material-ui-chameleon/blob/master/docs/webpack.config.js), this is my other package's documentation builder. I am sure you would appreciate the speed improvement.

**Comment by davityavryan** [comment]
Also you can do

`yarn upgrade-interactive` which will show you "safe" to upgrade (minor or patch) versions of packages, which in theory will not introduce any breaking changes.
`yarn upgrade-interactive --latest` will show you with breaking changes. But I would do this one separately.

And if you will run [yarn-deduplicate](https://www.npmjs.com/package/yarn-deduplicate) package after your upgrades, you will also eliminate all duplicated dependencies. (yarn does deduplication, but it is not 100% good one). This will also speed up install of packages and you will have less vulnerabilities and less packages to maintain.

Remember less packages --> less vulnerabilities ;)

p.s. I am working on a tool which is based on this one which can be used on PRs and show newly introduced vulnerabilities only.

**Comment by davityavryan** [comment]
@kenlyon this is your audit file. sorry I am still working on fixing the issue. But this is the first result.
[yarn-audit.html.zip](https://github.com/davityavryan/yarn-audit-html/files/6481731/yarn-audit.html.zip)

**Comment by davityavryan** [comment]
Hey @kenlyon

Try new `yarn-audit-html@^3.0.0` released version. I tried with your log and it is taking from 2 to 3 minutes to generate the report, but at least it is working :) (and for that huge audit log file, it is kind of ok IMO).

Changes included:
https://github.com/davityavryan/yarn-audit-html/releases/tag/v2.1.0
https://github.com/davityavryan/yarn-audit-html/releases/tag/v3.0.0

Let me know if you experience any issues (including PowerShell, I did not check in there, sorry).

If everything is ok, then close this issue and feel free to ☕, if you will. If it is not yet fixed, well ping me :)

[![Buy me a coffee](https://www.buymeacoffee.com/assets/img/custom_images/orange_img.png)](https://www.buymeacoffee.com/davityavryan)

**Comment by kenlyon** [comment]
Thanks for the quick fix. This works really well. I'm fine with the time it take to run. It works and that's the main thing.

I tested with Git Bash, Command Prompt and PowerShell. The first two worked fine, but PowerShell still failed with the same error as before. It's ok, though. I was just going through the options in Visual Studio Code, and I can always use the other two.

Thanks again!
